"""Initial schema with UUID IDs

Revision ID: 3432a21994e9
Revises: 
Create Date: 2025-04-26 02:58:27.425686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3432a21994e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_users_id'), ['id'], unique=False)

    op.create_table('promotions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_promotions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_is_active'), ['is_active'], unique=False)

    op.create_table('games',
    sa.Column('rawg_id', sa.Integer(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('released_date', sa.Date(), nullable=True),
    sa.Column('background_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_top', sa.Integer(), nullable=True),
    sa.Column('ratings_count', sa.Integer(), nullable=True),
    sa.Column('metacritic', sa.Integer(), nullable=True),
    sa.Column('playtime', sa.Integer(), nullable=True),
    sa.Column('suggestions_count', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_is_custom'), ['is_custom'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_rawg_id'), ['rawg_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_slug'), ['slug'], unique=True)

    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_customer_email'), ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('shopping_carts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_carts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_carts_user_id'), ['user_id'], unique=True)

    op.create_table('cart_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_carts.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_entries_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_entries_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_entries_id'), ['id'], unique=False)

    op.create_table('gamepromotionlink',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('promotion_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'promotion_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_game_id'))

    op.drop_table('order_items')
    op.drop_table('gamepromotionlink')
    with op.batch_alter_table('cart_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_entries_id'))
        batch_op.drop_index(batch_op.f('ix_cart_entries_game_id'))
        batch_op.drop_index(batch_op.f('ix_cart_entries_cart_id'))

    op.drop_table('cart_entries')
    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_carts_user_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_carts_id'))

    op.drop_table('shopping_carts')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_email'))

    op.drop_table('orders')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_slug'))
        batch_op.drop_index(batch_op.f('ix_games_rawg_id'))
        batch_op.drop_index(batch_op.f('ix_games_name'))
        batch_op.drop_index(batch_op.f('ix_games_is_custom'))
        batch_op.drop_index(batch_op.f('ix_games_id'))
        batch_op.drop_index(batch_op.f('ix_games_created_by_admin_id'))

    op.drop_table('games')
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotions_is_active'))
        batch_op.drop_index(batch_op.f('ix_promotions_id'))
        batch_op.drop_index(batch_op.f('ix_promotions_code'))

    op.drop_table('promotions')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_id'))
        batch_op.drop_index(batch_op.f('ix_app_users_email'))

    op.drop_table('app_users')
    # ### end Alembic commands ###
