"""Corrected initial migration

Revision ID: 74e34243a95f
Revises: 
Create Date: 2025-04-20 14:56:47.485077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74e34243a95f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_supabase_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_owner_supabase_id'), 'cart', ['owner_supabase_id'], unique=True)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_supabase_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_owner_supabase_id'), 'item', ['owner_supabase_id'], unique=False)
    op.create_table('promotion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_code'), 'promotion', ['code'], unique=True)
    op.create_index(op.f('ix_promotion_end_date'), 'promotion', ['end_date'], unique=False)
    op.create_index(op.f('ix_promotion_is_active'), 'promotion', ['is_active'], unique=False)
    op.create_index(op.f('ix_promotion_start_date'), 'promotion', ['start_date'], unique=False)
    op.create_table('cartitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartitem_cart_id'), 'cartitem', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cartitem_product_id'), 'cartitem', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartitem_product_id'), table_name='cartitem')
    op.drop_index(op.f('ix_cartitem_cart_id'), table_name='cartitem')
    op.drop_table('cartitem')
    op.drop_index(op.f('ix_promotion_start_date'), table_name='promotion')
    op.drop_index(op.f('ix_promotion_is_active'), table_name='promotion')
    op.drop_index(op.f('ix_promotion_end_date'), table_name='promotion')
    op.drop_index(op.f('ix_promotion_code'), table_name='promotion')
    op.drop_table('promotion')
    op.drop_index(op.f('ix_item_owner_supabase_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_cart_owner_supabase_id'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###
