"""sync

Revision ID: a7fc57995759
Revises: bd145e2e489b
Create Date: 2025-04-20 15:52:11.666183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7fc57995759'
down_revision: Union[str, None] = 'bd145e2e489b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customgame',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('released', sa.Date(), nullable=True),
    sa.Column('background_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customgame_name'), 'customgame', ['name'], unique=False)
    op.create_index(op.f('ix_customgame_slug'), 'customgame', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customgame_slug'), table_name='customgame')
    op.drop_index(op.f('ix_customgame_name'), table_name='customgame')
    op.drop_table('customgame')
    # ### end Alembic commands ###
