version: "3.8"

services:
  backend:
    build:
      context: ./apps/backend # Path to the backend directory containing Dockerfile
      dockerfile: Dockerfile
    container_name: backend_service
    volumes:
      # Mount the backend code for development (reflects changes without rebuild)
      # Comment out or remove for production builds
      - ./apps/backend:/app
    env_file:
      - ./apps/backend/.env # Load environment variables from this file
    network_mode: host # Use host network
    restart: unless-stopped
    # If using --reload with uvicorn, ensure stdin_open and tty are true
    # stdin_open: true
    # tty: true

  frontend:
    build:
      context: ./apps/frontend # Assuming Dockerfile is in apps/frontend
      dockerfile: Dockerfile # Assuming Dockerfile name
    container_name: frontend_service
    volumes:
      # Mount source code for development (adjust if frontend Dockerfile uses a different workdir)
      - ./apps/frontend:/app
      # Mount node_modules as a separate volume to avoid overwriting container modules
      - /app/node_modules
    environment:
      # Example: Tell frontend where backend is (though localhost should work with host network)
      # If using Vite/React, VITE_API_URL might be the convention
      # Point to backend service using its service name on the Docker network
      - VITE_API_URL=http://localhost:8000/api/v1
    network_mode: host # Use host network
    restart: unless-stopped
