version: "3.8"

services:
  backend:
    build: ./apps/backend
    network_mode: host
    volumes:
      # Mount source code for development (adjust if backend Dockerfile uses a different workdir)
      - ./apps/backend:/app
    environment:
      # Add any backend-specific environment variables here
      - DATABASE_URL=your_database_connection_string
      - SECRET_KEY=your_backend_secret_key
      # HOST_PORT=5000 # Example, might be needed if backend needs to know its host port

  frontend:
    build: ./apps/frontend
    network_mode: host
    volumes:
      # Mount source code for development (adjust if frontend Dockerfile uses a different workdir)
      - ./apps/frontend:/app
      # Mount node_modules as a separate volume to avoid overwriting container modules
      - /app/node_modules
    environment:
      # Example: Tell frontend where backend is (though localhost should work with host network)
      # If using Vite/React, VITE_API_URL might be the convention
      - VITE_API_URL=http://localhost:5000/api # Adjust port if backend runs elsewhere
    depends_on:
      - backend
# Add other services like databases if needed, potentially also on host network
# or using a bridge network if preferred.
# Example database (using bridge network):
# database:
#   image: postgres:15
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   environment:
#     - POSTGRES_DB=myappdb
#     - POSTGRES_USER=user
#     - POSTGRES_PASSWORD=password
#   networks:
#     - default # Default bridge network

# volumes:
#   postgres_data:
